[package]
name = "ckb-standalone-debugger"
description = "Standalone debugger for Nervos CKB"
version = "0.5.0-rc1"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
exclude = ["bins", "js"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ckb-chain-spec = { git="https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-error = { git="https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-traits = { git="https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-types = { git="https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-jsonrpc-types = { git="https://github.com/nervosnetwork/ckb", branch = "develop" }
ckb-script = { git="https://github.com/nervosnetwork/ckb", branch = "develop", default-features = false, features = ["detect-asm"] }
faster-hex = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_plain = "0.3.0"

js-sys = "0.3.27"
wasm-bindgen = "0.2.50"

[dev-dependencies]
byteorder = "1.3.2"
