[package]
name = "ckb-vm-syscall-tracer"
version.workspace = true
description = "A utility that runs a CKB transaction, and then gathers syscall input/outputs for each individual VM instances to seperate files"
edition = "2021"
autobins = false

[[bin]]
name = "ckb-vm-syscall-tracer"
path = "src/tracer.rs"

[features]
default = []
asm = ["ckb-script/asm"]

[dependencies]
ckb-chain-spec.workspace = true
ckb-mock-tx-types.workspace = true
ckb-script.workspace = true
ckb-types.workspace = true
ckb-traits.workspace = true
ckb-vm.workspace = true
prost.workspace = true
serde_json.workspace = true

clap = { version = "4.5.32", features = ["cargo", "derive"] }
int-enum = "1.1.2"

[build-dependencies]
prost-build.workspace = true
